"""cria tabelas iniciais

Revision ID: 34042df99899
Revises: 
Create Date: 2026-09-10 17:26:40.618113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34042df99899'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento_agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('palestra', 'trabalho', 'grupo', 'outro', name='tipoevento', native_enum=False, length=20), nullable=False),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorrencia', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcao_trabalhador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.Enum('masculino', 'feminino', 'outro', 'nao_informado', name='sexo', native_enum=False, length=20), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('logradouro', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('como_conheceu', sa.String(length=255), nullable=True),
    sa.Column('observacoes_gerais', sa.Text(), nullable=True),
    sa.Column('consentimento_lgpd', sa.Boolean(), nullable=False),
    sa.Column('consentimento_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_pessoa_cpf', 'pessoa', ['cpf'], unique=True, postgresql_where=sa.text('cpf IS NOT NULL'))
    op.create_table('tipo_tratamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('formato', sa.Enum('individual', 'grupo', 'caso', name='formatotratamento', native_enum=False, length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.Enum('admin', 'operador', name='papelusuario', native_enum=False, length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('atendimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('atendido_por_id', sa.Integer(), nullable=True),
    sa.Column('solicitante_id', sa.Integer(), nullable=True),
    sa.Column('presente', sa.Boolean(), nullable=False),
    sa.Column('modalidade', sa.Enum('presencial', 'video', 'distancia', name='modalidade', native_enum=False, length=20), nullable=False),
    sa.Column('ordem_chegada', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('retorno_previsto', sa.Date(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['atendido_por_id'], ['pessoa.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solicitante_id'], ['pessoa.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.Enum('criar', 'atualizar', 'excluir', 'login', name='acaoauditoria', native_enum=False, length=20), nullable=False),
    sa.Column('entidade', sa.String(length=50), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('dados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('funcao', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['evento_agenda.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evento_id', 'pessoa_id', name='uq_escala')
    )
    op.create_table('pessoa_papel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.Enum('trabalhador', 'assistido', name='papel', native_enum=False, length=20), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pessoa_id', 'papel', name='uq_pessoa_papel')
    )
    op.create_table('pessoa_vinculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('relacionado_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('pai', 'mae', 'filho', 'filha', 'conjuge', 'irmao', 'avo', 'neto', 'amigo', 'responsavel', 'outro', name='tipovinculo', native_enum=False, length=20), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.CheckConstraint('pessoa_id <> relacionado_id', name='ck_vinculo_pessoas_diferentes'),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relacionado_id'], ['pessoa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pessoa_id', 'relacionado_id', 'tipo', name='uq_pessoa_vinculo')
    )
    op.create_table('sessao_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_tratamento_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['responsavel_id'], ['pessoa.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tipo_tratamento_id'], ['tipo_tratamento.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trabalhador_funcao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('funcao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funcao_id'], ['funcao_trabalhador.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pessoa_id', 'funcao_id', name='uq_trabalhador_funcao')
    )
    op.create_table('tratamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_tratamento_id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('sessoes_previstas', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('em_andamento', 'concluido', name='statustratamento', native_enum=False, length=20), nullable=False),
    sa.Column('situacao_final', sa.Text(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solicitante_id'], ['pessoa.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tipo_tratamento_id'], ['tipo_tratamento.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atendimento_tratamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('tipo_tratamento_id', sa.Integer(), nullable=False),
    sa.Column('modalidade', sa.Enum('presencial', 'video', 'distancia', name='modalidade', native_enum=False, length=20), nullable=True),
    sa.Column('sessoes_previstas', sa.Integer(), nullable=True),
    sa.Column('sessoes_realizadas', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimento.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_tratamento_id'], ['tipo_tratamento.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presenca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessao_grupo_id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sessao_grupo_id'], ['sessao_grupo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sessao_grupo_id', 'pessoa_id', name='uq_presenca')
    )
    op.create_table('tratamento_assistido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tratamento_id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ativo', 'concluido', 'removido', name='statusassistido', native_enum=False, length=20), nullable=False),
    sa.Column('situacao_final', sa.Text(), nullable=True),
    sa.Column('data_conclusao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tratamento_id'], ['tratamento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tratamento_id', 'pessoa_id', name='uq_tratamento_assistido')
    )
    op.create_table('tratamento_evolucao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tratamento_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=True),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['pessoa.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tratamento_id'], ['tratamento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tratamento_evolucao')
    op.drop_table('tratamento_assistido')
    op.drop_table('presenca')
    op.drop_table('atendimento_tratamento')
    op.drop_table('tratamento')
    op.drop_table('trabalhador_funcao')
    op.drop_table('sessao_grupo')
    op.drop_table('pessoa_vinculo')
    op.drop_table('pessoa_papel')
    op.drop_table('escala')
    op.drop_table('audit_log')
    op.drop_table('atendimento')
    op.drop_table('usuario')
    op.drop_table('tipo_tratamento')
    op.drop_index('uq_pessoa_cpf', table_name='pessoa', postgresql_where=sa.text('cpf IS NOT NULL'))
    op.drop_table('pessoa')
    op.drop_table('funcao_trabalhador')
    op.drop_table('evento_agenda')
    # ### end Alembic commands ###
