"""adiciona voluntario, estado civil e quantidade de filhos

Revision ID: 5df0cbfeb6fe
Revises: 99cafb879563
Create Date: 2026-09-13 11:15:57.007045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df0cbfeb6fe'
down_revision: Union[str, None] = '99cafb879563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoa', sa.Column('estado_civil', sa.Enum('solteiro', 'casado', 'uniao_estavel', 'divorciado', 'viuvo', 'nao_informado', name='estadocivil', native_enum=False, length=20), server_default='nao_informado', nullable=False))
    op.add_column('pessoa', sa.Column('quantidade_filhos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # não gerado pelo autogenerate (ele não compara CHECK constraints)
    op.create_check_constraint(
        'ck_pessoa_quantidade_filhos_positiva',
        'pessoa',
        'quantidade_filhos IS NULL OR quantidade_filhos >= 0',
    )

    # "voluntario" no papel de pessoa e "nao_informado" no estado civil não
    # exigem migração: essas colunas são VARCHAR simples (sem CHECK do banco),
    # a validação de valores permitidos é feita pelo Pydantic.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_pessoa_quantidade_filhos_positiva', 'pessoa', type_='check')
    op.drop_column('pessoa', 'quantidade_filhos')
    op.drop_column('pessoa', 'estado_civil')
    # ### end Alembic commands ###
