"""adiciona vinculo do assistido com o responsavel (filho, amigo etc)

Revision ID: 6ecffe119883
Revises: ec4219cdebc9
Create Date: 2026-09-13 11:57:12.141068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ecffe119883'
down_revision: Union[str, None] = 'ec4219cdebc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tratamento_assistido', sa.Column('vinculo_com_responsavel', sa.Enum('pai', 'mae', 'filho', 'filha', 'conjuge', 'irmao', 'avo', 'neto', 'amigo', 'responsavel', 'outro', name='tipovinculo', native_enum=False, length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tratamento_assistido', 'vinculo_com_responsavel')
    # ### end Alembic commands ###
