"""cria tabela de anexos (fotos e documentos)

Revision ID: ec4219cdebc9
Revises: 76b6b68697f0
Create Date: 2026-09-13 11:34:10.924380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec4219cdebc9'
down_revision: Union[str, None] = '76b6b68697f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anexo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=True),
    sa.Column('tratamento_id', sa.Integer(), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('tipo_conteudo', sa.String(length=100), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.LargeBinary(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('enviado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT (atendimento_id IS NOT NULL AND tratamento_id IS NOT NULL)', name='ck_anexo_um_so_vinculo'),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimento.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enviado_por_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tratamento_id'], ['tratamento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anexo_pessoa_id'), 'anexo', ['pessoa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anexo_pessoa_id'), table_name='anexo')
    op.drop_table('anexo')
    # ### end Alembic commands ###
